apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  app: shoppingapi-hpa
spec:
  maxReplicas: 10 #max replica counts
  minReplicas:  3 # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoppingapi-deployment
  targetCPUUtilizationPercentage: 100 #target cpu utilization as we only have one microservice but make sure 
                                  # the resource section of your pods have enough setup number of cpu.